autoInstallPeers: false

catalog:
  oxlint: ^1.57.0

onlyBuiltDependencies:
  - esbuild

overrides:
  vite-plus>oxfmt: '-'
  vite-plus>oxlint: 'catalog:'

peerDependencyRules:
  allowAny:
    - typescript
    - vitest
  ignoreMissing:
    - oxlint-tsgolint

strictPeerDependencies: true

trustPolicy: no-downgrade

updateConfig:
  ignoreDependencies:
    - '@types/node'
