autoInstallPeers: false

onlyBuiltDependencies:
  - esbuild

peerDependencyRules:
  allowAny:
    - eslint
    - typescript
    - vitest

strictPeerDependencies: true

updateConfig:
  ignoreDependencies:
    - '@types/node'
