autoInstallPeers: false

blockExoticSubdeps: true

catalog:
  oxlint: ^1.59.0

onlyBuiltDependencies:
  - esbuild

overrides:
  '@eslint/config-helpers': 0.5.3
  '@napi-rs/wasm-runtime': 1.1.1
  vite-plus>oxfmt: '-'
  vite-plus>oxlint: 'catalog:'

peerDependencyRules:
  allowAny:
    - oxlint-tsgolint
    - vitest

strictPeerDependencies: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - undici-types

updateConfig:
  ignoreDependencies:
    - '@types/node'
